language: node_js

node_js:
  - "12"

addons:
    sonarcloud:
        organization: "csc47300" # the key of the org you chose at step #3
        token: "f55dbda5810f7c1bb8ba267f3a7ad75348b28ea0"
            #secure: "f55dbda5810f7c1bb8ba267f3a7ad75348b28ea0" # encrypted value of your token

script:
    - cd webpage && npm install
    - cd webpage && npm test
    - cd webpage && npm run build
    - sonar-scanner